services:
  - type: web
    name: sistema-comercial-bazar
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_SEED_CATALOG
        value: "true"
      - key: JDBC_DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
